<?php
use SimpleHtml\Common\Page\Edit;
use SimpleHtml\Common\Security\Profile;
use SimpleHtml\Common\Generic\Messages;
// process contact post (if any)
// $OBJ == calling instance
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
// check to see if authenticated
if (Profile::verify($config) === FALSE) {
    Profile::logout();
    $message = Messages::getInstance();
    $message->addMessage('Unable to authenticate');
    header('Location: /');
    exit;
}
// init vars
$edit     = new Edit($config);
$contents = '';
// build dropdown list of existing pages
$pages = $edit->getListOfPages();
$select = '<select name="page_key" class="form-control" placeholder="Choose">' . PHP_EOL;
$select .= '<option>' . Edit::CHOOSE_TOP . '</option>' . PHP_EOL;
foreach (array_keys($pages) as $key)
    $select .= '<option>' . $key . '</option>' . PHP_EOL;
$select .= '</select>' . PHP_EOL;
// get messages
$message = Messages::getInstance();
$msg     = $message->getMessages() ?? 'Select page to edit or delete.  To add a new page, enter a URL and click "Add New Page" button.';
?>
  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Choose</h1>
          <p class="lead mb-5 text-white-50">Use this page choose the web page you wish to edit or delete. To add a new page, enter a URL and click "Add New Page" button.</p>
          <?php include ($config['SUPER']['super_menu'] ?? '') ?>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
        <div class="col-lg-6">
            <!-- Edit Form -->
            <form class="choose_form" action="/super/edit" method="get">

                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Enter URL (or choose from Page List)
                                <span class="text-danger">*</span>
                            </label>
                            <div class="input-group">
                                <input class="form-control" name="page_url" id="page_url" size=60 placeholder="http://company.com/page/title" type="text" />
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->
                </div>
                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Choose from Page List (or Enter URL)
                                <span class="text-danger">*</span>
                            </label>
                            <div class="input-group"><?= $select ?></div>
                        </div>
                    </div>
                    <!-- End Input -->
                </div>
                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <input name="choose_edit_page" type="submit" class="btn btn-primary btn-circled" value="Edit Existing Page">
                            <input name="choose_new_page" type="submit" class="btn btn-primary btn-circled" value="Add New Page">
                            <input name="choose_del_page" type="submit" class="btn btn-primary btn-circled" value="Delete Page">
                        </div>
                    </div>
                    <!-- End Input -->
                </div><!-- row -->

            </form>
            <!-- End Edit Form -->
           <!-- form message -->
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success contact__msg">
                        <?= $msg ?>
                    </div>
                </div>
            </div>
            <!-- end message -->
        </div>

    </div>
  </div>
