<?php
use SimpleHtml\Common\Page\Edit;
use SimpleHtml\Common\Security\Profile;
use SimpleHtml\Common\Generic\Messages;
// process contact post (if any)
// $OBJ == calling instance
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
// check to see if authenticated
if (Profile::verify($config) === FALSE) {
    Profile::logout();
    $message = Messages::getInstance();
    $message->addMessage('Unable to authenticate');
    header('Location: /');
    exit;
}
// init vars
$edit     = new Edit($config);
$contents = '';
$message  = Messages::getInstance();
// determine action
$action = (!empty($_POST['new_page'])) ? 'add' : 'edit';
// if edit, get contents
if ($action === 'edit') {
    $key = $_POST['page_key'] ?? '';
    // get page contents via key
    if (!empty($_POST['page_key'])) {
        $contents = $edit->getContentsFromPage($_POST['page_key'], HTML_DIR);
    // get page contents via url
    } elseif (!empty($_POST['page_url'])) {
        $key = $edit->getKeyFromURL($_POST['page_url']);
        $contents = $edit->getContentsFromPage($key, HTML_DIR);
    // save data?
    } elseif (!empty($_POST['save'])) {
        $messages->addMessage();
    }
}
// get messages
$msg = $message->getMessages() ?? var_export($_GET, TRUE);
?>
  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Edit</h1>
          <p class="lead mb-5 text-white-50">Use this page to edit web pages.</p>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
        <div class="col-lg-6">
            <!-- Edit Form -->
            <form class="contact_form" action="/super/edit" method="post">
                <div class="row">

                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Page Editor
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group">
                                <textarea id="page_edit" type="textarea" name="page_edit" rows="20" cols="70"><?= $contents ?></textarea><br><br>
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->
                </div>
                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <div class="input-group">
                                <input name="save" type="submit" class="btn btn-primary btn-circled" value="Save">
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->
                </div>
            </form>
            <!-- End Edit Form -->
           <!-- form message -->
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success contact__msg">
                        <?= $msg ?>
                    </div>
                </div>
            </div>
            <!-- end message -->
        </div>

    </div>
  </div>
    <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
    <script type="text/javascript">
    CKEDITOR.replace('page_edit', {
        startupFocus: true,
        filebrowserUploadUrl: '/super/upload'
    });
    </script>
