<?php
use SimpleHtml\Common\Page\Edit;
use SimpleHtml\Common\Security\Profile;
use SimpleHtml\Common\Generic\Registry;
// process contact post (if any)
// $OBJ == calling instance
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
// check to see if authenticated
if (Profile::verify() === FALSE) {
    Registry::set('msg', 'Unable to authenticate');
    header('Location: /super/login');
    exit;
}
// init vars
$edit     = new Edit($config);
$contents = '';
// check to make sure user is "super"
$msg = $_SESSION['super'] ?? '';
?>
  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Edit</h1>
          <p class="lead mb-5 text-white-50">Use this page to edit web pages.</p>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
        <div class="col-lg-6">
            <!-- Edit Form -->
            <form class="contact_form" action="/super/edit" method="post">
                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Enter Page URL
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group">
                                <input class="form-control" name="page_url" id="page_url" required="1" placeholder="http://company.com/page/title" type="text" />
                                <input class="form-control" name="page_new" id="page_new" title="Checkmark this if it's a new page" type="checkbox" value="1" />
                                New Page
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->
                </div>
                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Page Editor
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group">
                                <textarea id="page_edit" type="textarea" name="page_edit" rows="20" cols="70"><?= $contents ?></textarea><br><br>
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->

                    <?php if (!empty($other)) : ?>
                    <!-- Input -->
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                <?= ucfirst($other) ?>
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group">
                                <input class="form-control" name="other" id="other" required="1" placeholder="<?= ucfirst($other) ?>" type="text">
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->
                    <?php endif; ?>

                <div class="">
                    <input name="submit" type="submit" class="btn btn-primary btn-circled" value="Submit">
                </div>
            </form>
            <!-- End Edit Form -->
           <!-- form message -->
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success contact__msg">
                        <?= $msg ?>
                    </div>
                </div>
            </div>
            <!-- end message -->
        </div>

    </div>
  </div>
    <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
    <script type="text/javascript">
    CKEDITOR.replace('page_edit', {
        startupFocus: true,
        filebrowserUploadUrl: '/super/upload'
    });
    </script>
