<?php
use SimpleHtml\Common\Image\Captcha;
// process contact post (if any)
// $OBJ == calling instance
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
$hashKey = $config['CAPTCHA']['sess_hash_key'] ?? 'hash';
$max = $config['SUPER']['attempts'] ?? 3;
$msg = 'Enter your login information';
$other = [];
if ($_POST) {
    // capture login params
    $name   = $_POST['name']     ?? 'Default';
    $pwd    = $_POST['password'] ?? 'Default';
    $phrase = $_POST['phrase']   ?? 'Default';
    $other  = $_POST['other']    ?? '';
    // get valid info
    $valid_name  = $config['SUPER']['username'] ?? 'Not Set';
    $valid_pwd   = $config['SUPER']['password'] ?? 'Not Set';
    $valid_other = $_SESSION['other'] ?? 'Not Set';
    $valid_hash  = $_SESSION[$hashKey] ?? 'Not Set';
    // expected results
    $expected = 3;
    // validate login
    $valid = 0;
    $valid += (int) ($name === $valid_name);
    $valid += (int) ($pwd  === $valid_pwd);
    $valid += (int) password_verify($phrase, $valid_hash);
    if (!empty($other)) {
        $expected++;
        $valid += (int) ($other === $valid_other);
    }
    if ($valid === $expected) {
        // store md5 of selected $_SERVER array settings
        $_SESSION['super'] = '';
        // redirect to "super" area
        header('Location: /super/edit');
        exit;
    } else {
        $msg = $config['SUPER']['message'] ?? 'Unable to login';
    }
    $msg = var_export($_POST, TRUE);
    $msg .= var_export($_SESSION, TRUE);
}
// login attempt control
$attempts = $_SESSION['attempts'] ?? 0;
$_SESSION['attempts'] = ++$attempts;
if ($attempts > $max) {
    $validation = $config['SUPER']['validation'] ?? [];
    if (!empty($validation)) {
        $count = count($validation);
        $idx   = rand(1, $count) - 1;
        $key   = array_keys($validation)[$idx] ?? '';
        if (!empty($validation[$key])) {
            $other = $key;
            $_SESSION['other'] = $validation[$key];
        }
    }
}
// generate CAPTCHA
$token   = bin2hex(random_bytes(4));
$captcha = new Captcha($config['CAPTCHA']);
$images  = $captcha->writeImages($token);
$hash    = password_hash($captcha->phrase, PASSWORD_BCRYPT);
$_SESSION[$hashKey] = $hash;
?>
  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Login</h1>
          <p class="lead mb-5 text-white-50">Use this page to login to the content editor.</p>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
        <div class="col-lg-6">
            <!-- Contacts Form -->
            <form class="contact_form" action="/super/login" method="post">
                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Username
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group">
                                <input class="form-control" name="name" id="name" required="1" placeholder="John Doe" type="text">
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->

                    <!-- Input -->
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Password
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group">
                                <input class="form-control" name="password" id="password" required="1" placeholder="Password" type="password">
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->

                    <?php if (!empty($other)) : ?>
                    <!-- Input -->
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                <?= ucfirst($other) ?>
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group">
                                <input class="form-control" name="other" id="other" required="1" placeholder="<?= ucfirst($other) ?>" type="text">
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->
                    <?php endif; ?>

                <div class="">
                    <br />
                    &nbsp;&nbsp;Prove you're human! Enter the characters below:<br />&nbsp;&nbsp;
                    <?php foreach ($images as $fn) : ?><img src="/img/captcha/<?= $fn; ?>" style="width:50px;height:auto;" /><?php endforeach; ?>
                    &nbsp;<input type="text" name="phrase" placeholder="I'm not a robot" /><br /><br />
                    <input type="hidden" id="source" name="source" value="<?= $config['HOST'] . $uri; ?>">
                    <input name="submit" type="submit" class="btn btn-primary btn-circled" value="Login">

                </div>
            </form>
            <!-- End Contacts Form -->
           <!-- form message -->
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success contact__msg">
                        <?= $msg ?>
                    </div>
                </div>
            </div>
            <!-- end message -->
        </div>

        <div class="col-lg-6 col-md-6">
            <!-- START MAP -->
            <div id="map" ></div>
            <!-- END MAP -->
        </div>
    </div>
  </div>
