<?php
use EasierThanWordPress\Common\Image\Captcha;
use EasierThanWordPress\Common\Contact\{Email,Storage};
// process contact post (if any)
// $OBJ == calling instance
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
if ($_POST) {
    $body = '';
    $log = $config['CONTACT_LOG'];
    $inputs = $_POST;
    $msg = Email::processPost($config, $inputs, $body);
    // store message in database
    $storage = new Storage($config);
    $storage->save('contacts', $inputs);
    // log body + message
    $body .= ($msg) ? "\n$msg\n" : '';
    if ($body) {
        file_put_contents($log, $body, FILE_APPEND);
    }
}
// generate CAPTCHA
$hashKey = $config['CAPTCHA']['sess_hash_key'] ?? 'hash';
$token   = bin2hex(random_bytes(4));
$captcha = new Captcha($config['CAPTCHA']);
$images  = $captcha->writeImages($token);
$hash    = password_hash($captcha->phrase, PASSWORD_BCRYPT);
$_SESSION[$hashKey] = $hash;
?>
  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Leave a Message</h1>
          <p class="lead mb-5 text-white-50">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non possimus ab labore provident mollitia. Id assumenda voluptate earum corporis facere quibusdam quisquam iste ipsa cumque unde nisi, totam quas ipsam.</p>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
        <div class="col-lg-6">
           <!-- form message -->
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success contact__msg" style="display: none" role="alert">
                        <?= $msg ?>
                    </div>
                </div>
            </div>
            <!-- end message -->
            <!-- Contacts Form -->
            <form class="contact_form" action="mail.php">
                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Your name
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group">
                                <input class="form-control" name="name" id="name" required="" placeholder="John Doe" type="text">
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->

                    <!-- Input -->
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Your email address
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group ">
                                <input class="form-control" name="email" id="email" required="" placeholder="john@gmail.com" type="email">
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->

                    <div class="w-100"></div>

                    <!-- Input -->
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Subject
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group">
                                <input class="form-control" name="subject" id="subject" required="" placeholder="Website Quote" type="text">
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->

                    <!-- Input -->
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Your Phone Number
                                <span class="text-danger">*</span>
                            </label>

                            <div class="input-group ">
                                <input class="form-control" id="phone" name="phone" required="" placeholder="1-800-643-4500" type="text">
                            </div>
                        </div>
                    </div>
                    <!-- End Input -->
                </div>

                <!-- Input -->
                <div class="form-group mb-5">
                    <label class="h6 small d-block text-uppercase">
                        How can we help you?
                        <span class="text-danger">*</span>
                    </label>

                    <div class="input-group">
                        <textarea class="form-control" rows="4" name="message" id="message" required="" placeholder="Hello, I would like to ..."></textarea>
                    </div>
                </div>
                <!-- End Input -->

                <div class="">
                    <br />
                    &nbsp;&nbsp;Prove you're human! Enter the characters below:<br />&nbsp;&nbsp;
                    <?php foreach ($images as $fn) : ?><img src="/img/captcha/<?= $fn; ?>" style="width:50px;height:auto;" /><?php endforeach; ?>
                    &nbsp;<input type="text" name="phrase" placeholder="I'm not a robot" /><br /><br />
                    <input type="hidden" id="source" name="source" value="<?= $config['HOST'] . $uri; ?>">
                    <input name="submit" type="submit" class="btn btn-primary btn-circled" value="Send Message">

                    <p class="small pt-3">We'll get back to you in 1-2 business days.</p>
                </div>
            </form>
            <!-- End Contacts Form -->
        </div>

        <div class="col-lg-6 col-md-6">
            <!-- START MAP -->
            <div id="map" ></div>
            <!-- END MAP -->
        </div>
    </div>
  </div>
