<?php
use SimpleHtml\Common\Page\Edit;
use SimpleHtml\Common\Security\Profile;
use SimpleHtml\Common\Generic\Messages;
// process contact post (if any)
// $OBJ == calling instance (usually from /public/index.php)
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
// check to see if authenticated
$message  = Messages::getInstance();
if (Profile::verify($config) === FALSE) {
    Profile::logout();
    $message->addMessage('Unable to authenticate');
    header('Location: /');
    exit;
}
// init vars
$key      = '';
$edit     = new Edit($config);
$contents = '';
$edit_width = $config['SUPER']['ckeditor']['width'] ?? 900;
$edit_height = $config['SUPER']['ckeditor']['height'] ?? 500;
$super_url   = $config['SUPER']['super_url'] ?? Edit::DEFAULT_SUPER;
// acquire key and page_url
$key      = $_REQUEST['page_key'] ?? '';
$key      = ($key === Edit::CHOOSE_TOP) ? '' : $key;
$page_url = $_REQUEST['page_url'] ?? '';
// go to choose if both indicators are empty
if (empty($key)) {
    if (empty($page_url)) {
        header('Location: /super/choose');
        exit;
    }
    $key = $edit->getKeyFromURL($page_url);
}
// determine action
if (!empty($_POST)) {
    // cancel option
    if (isset($_POST['cancel'])) {
        $message->addMessage(Edit::SUCCESS_CANCEL);
    } elseif (isset($_POST['save']) && $_POST['save'] === 'Delete') {
        if (isset($_POST['page_del']) && $_POST['page_del'] === 'Y') {
            if ($edit->delete($key) === TRUE) {
                $message->addMessage(Edit::SUCCESS_DEL);
            } else {
                $message->addMessage(Edit::ERROR_DEL);
            }
        } else {
            $message->addMessage(Edit::SUCCESS_CANCEL);
        }
    } elseif (isset($_POST['choose'])) {
        header('Location: /super/choose');
        exit;
    } else {
        // save data
        $data = $_POST['page_content'] ?? '';
        if (!$edit->save($key, $data, HTML_DIR, TRUE)) {
            $message->addMessage(Edit::ERROR_SAVE);
        } else {
            $message->addMessage(Edit::SUCCESS_SAVE);
        }
        $action = 'edit';
    }
}
if (isset($_GET['choose_edit_page'])) {
    $action = 'edit';
} elseif (isset($_GET['choose_del_page'])) {
    $action = 'delete';
} else {
    $action = 'edit';
}
if ($action === 'edit' || $action === 'delete') {
    $contents = $edit->getContentsFromPage($key, HTML_DIR);
}
// get messages
$msg = $message->getMessages() ?? 'Edit as appropriate and click "Save" when done';
?>
  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2"><?= ucfirst($action) ?></h1>
          <p class="lead mb-5 text-white-50">Use this page to edit web pages.</p>
          <?php include $config['SUPER']['super_menu'] ?? '' ?>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <!-- Edit Form -->
            <form class="contact_form" action="<?= $super_url ?>/edit" method="post">

                <!-- Input -->
                <div class="row">
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                URL
                                <span class="text-danger">*</span>
                            </label>

                            <div>
                                <input type="text" id="page_key" name="page_key" size=60 value="<?= $key ?>" />
                                &nbsp;
                                <a target="_blank" href="<?= $key ?>" title="This link only works after you have saved your work" />PREVIEW</a>
                                &nbsp;
                                <input name="choose" type="submit" class="btn btn-primary btn-circled" value="Back" title="Click here to choose another page to work with">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Input -->

                <?php if ($action === 'delete') : ?>
                <!-- Input -->
                <div class="row">
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Confirm Deletion
                                <span class="text-danger">*</span>
                            </label>

                            <div>
                                <input type="radio" id="page_del" name="page_del" value="Y" />&nbsp; Yes
                                <input type="radio" id="page_del" name="page_del" value="N" />&nbsp; No
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Input -->
                <?php endif; ?>

                <!-- Input -->
                <div class="row">
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Page Editor
                                <span class="text-danger">*</span>
                            </label>

                            <div>
                                <textarea id="page_content" type="textarea" name="page_content"><?= $contents ?></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Input -->

                <!-- Input -->
                <div class="row">
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <div class="input-group">
                                <?php $label = ($action === 'delete') ? 'Delete' : 'Save'; ?>
                                <input name="save" type="submit" class="btn btn-primary btn-circled" value="<?= $label ?>">
                                &nbsp;&nbsp;
                                <input name="choose" type="submit" class="btn btn-primary btn-circled" value="Back" title="Click here to choose another page to work with">
                                &nbsp;&nbsp;
                                <input name="cancel" type="submit" class="btn btn-primary btn-circled" value="Cancel">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Input -->

            </form>
            <!-- End Edit Form -->

           <!-- form message -->
            <div class="row">
                <div class="col-md-12">
                    <div class="alert alert-success contact__msg">
                        <?= $msg ?>
                    </div>
                </div>
            </div>
            <!-- end message -->

        </div>

    </div>
  </div>
    <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
    <script type="text/javascript">
    CKEDITOR.replace('page_content', {
        startupFocus: true,
        filebrowserImageUploadUrl: '/super/upload',
        filebrowserImageBrowseUrl: '/super/browse',
        filebrowserWindowWidth: '800',
        filebrowserWindowHeight: '500',
        width: '<?= $edit_width ?>',
        height: '<?= $edit_height ?>'
    });
    CKEDITOR.config.allowedContent = true;
    </script>
