<?php
use SimpleHtml\Transform\Import;
use SimpleHtml\Common\Page\Edit;
use SimpleHtml\Common\Security\Profile;
use SimpleHtml\Common\Generic\Messages;
// upload function
function do_import(string $url,
                   array $trusted,
                   array $transform,
                   string $delim_start,
                   $delim_stop,
                   Edit $edit,
                   Messages $message)
{
    if (!Import::is_trusted($url, $trusted)) return FALSE;
    set_time_limit(30);
    $ok   = FALSE;
    $html = Import::import($url, $transform, $delim_start, $delim_stop);
    if (empty($html)) {
        $message->addMessage(Import::ERROR_URL_EMPTY);
    } else {
        $key  = $edit->getKeyFromURL($url, HTML_DIR);
        if ($edit->save($key, $html, HTML_DIR, TRUE)) {
            $message->addMessage(Edit::SUCCESS_SAVE);
            $ok = TRUE;
        } else {
            $message->addMessage(Edit::ERROR_SAVE);
        }
    }
    return ($ok) ? $key : FALSE;
}
// process multiple imports
function do_bulk_import(array $list,
                        array $trusted,
                        array $transform,
                        string $delim_start,
                        string $delim_stop,
                        Edit $edit,
                        Messages $message)
{
    $bulk = [];
    foreach ($list as $url) {
        $url  = strip_tags(trim($url));
        $key = do_import($url, $trusted, $transform, $delim_start, $delim_stop, $edit, $message);
        if ($key !== FALSE) $bulk[] = $key;
    }
    return $bulk;
}
// process contact post (if any)
// $OBJ == calling instance
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
// check to see if authenticated and feature enabled
$enabled = (isset($config['IMPORT']['enable'])) ? $config['IMPORT']['enable'] : FALSE;
if (!$enabled || Profile::verify($config) === FALSE) {
    Profile::logout();
    $message = Messages::getInstance();
    $message->addMessage('Unable to authenticate');
    header('Location: /');
    exit;
}
// init vars
$total     = 0;
$key       = '';
$bulk      = [];
$edit      = new Edit($config);
$message   = Messages::getInstance();
$transform = $config['IMPORT']['transform'] ?? [];
$trusted   = $config['IMPORT']['trusted_src'] ?? [];
$super_url = $config['SUPER']['super_url'] ?? Edit::DEFAULT_SUPER;
$delim_start = $_POST['delim_start'] ?? $config['IMPORT']['delim_start'] ?? Import::DEFAULT_START;
// grab stop delimiter
if (!empty($_POST['delim_stop'])) {
    // if there's a comma, we need to produce an array of stops
    if (strpos($_POST['delim_stop'], ',') !== FALSE) {
        $delim_stop = explode(',', $_POST['delim_stop']);
    } else {
        $delim_stop = $_POST['delim_stop'];
    }
} else {
    // otherwise grab stop delim from config or use default
    $delim_stop = $config['IMPORT']['delim_stop']  ?? Import::DEFAULT_STOP;
}
$import_file_field = $config['IMPORT']['import_file_field'] ?? 'import_file';
// check to see if we need to import anything
if (!empty($_POST)) {
    $tmp_trans   = [];
    // if "import_url" is set, just import from the list
    if (!empty($_POST['import_url'])) {
        $url  = strip_tags($_POST['import_url']);
        $key = do_import($url, $trusted, $transform, $delim_start, $delim_stop, $edit, $message);
        if (!empty($key)) {
            header('Location: ' . $super_url . '/edit?page_key=' . $key);
            exit;
        }
    // check to see if "import_bulk" is set
    } elseif (!empty($_POST['import_bulk'])) {
        $temp = $_POST['import_bulk'] ?? '';
        //$temp = str_replace(PHP_EOL, ' ', $temp);
        $list = explode(PHP_EOL, trim($temp));
        if (empty($list)) {
            $message->addMessage(Import::ERROR_UPLOAD);
        } else {
            $bulk = do_bulk_import($list, $trusted, $transform, $delim_start, $delim_stop, $edit, $message);
        }
    // check to see if "import_file" is set
    } elseif (!empty($_FILES['import_file'])) {
        $list = Import::get_upload($import_file_field, $_FILES, $trusted);
        if (empty($list)) {
            $message->addMessage(Import::ERROR_UPLOAD);
        } else {
            $bulk = do_bulk_import($list, $trusted, $transform, $delim_start, $delim_stop, $edit, $message);
        }
    }
}
// get messages
$msg = $message->getMessages() ?? 'Enter a URL to import.  Alternatively you can upload a list of URLs of pages to import.';
if (!empty($bulk))
    foreach ($bulk as $key)
        $msg .= '<br /><a target="_blank" href="/super/edit?page_key=' . $key . '">' . $key . '</a>';
?>
  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Import</h1>
          <p class="lead mb-5 text-white-50">Use this page to import pages from another website.
          Enter a URL to import or upload a list of URLs of pages to import.
          Checkmark any transformation filters you wish to apply to imported HTML.
          To expand the number of transformation filters you need to add to the <i>IMPORT::transform</i> configuration.</p>
          <?php include ($config['SUPER']['super_menu'] ?? '') ?>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <!-- Edit Form -->
            <form class="choose_form" action="<?= $super_url ?>/import" method="post" enctype="multipart/form-data">

                <div class="row">
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Manually a Single URL to Import
                                <span class="text-danger">*</span>
                            </label>
                            <div class="input-group">
                                <input class="form-control" name="import_url" id="import_url" size=60 placeholder="http://company.com/page/one.html" type="text" title="Enter single URL" value="" />
                            </div>
                            <p>(or enter bulk list of URLs to automatically import)</p>
                            <hr />
                        </div>
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Enter Bulk List URLs to Import
                                <span class="text-danger">*</span>
                            </label>
                            <div class="input-group">
                                <textarea class="form-control" name="import_bulk" id="import_bulk" rows=4 cols=80 title="Enter single URL, or a list of URLs, one per line" ></textarea>
                            </div>
                            <p>(or upload a single URL to import)</p>
                            <hr />
                        </div>
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Upload File with List of URLs to Automatically Import
                                <span class="text-danger">*</span>
                            </label>
                            <div class="input-group"><input type="file" name="<?= $import_file_field ?>" /></div>
                            <p>(or manually enter one or more URLs to import)</p>
                            <hr />
                        </div>
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Start / Stop Delimiters
                                <span class="text-danger">*</span>
                            </label>
                            <div class="input-group">
                                <input class="form-control" name="delim_start" id="delim_start" size=40 placeholder="&lt;body&gt;" type="text" title="Delimiter that tells import where to start extracting HTML content" value="<?= htmlspecialchars($delim_start); ?>" />
                                <input class="form-control" name="delim_stop" id="delim_stop" size=40 placeholder="&lt;/body&gt;" type="text" title="Delimiter that tells import where to stop extracting HTML content" value="<?= htmlspecialchars((is_array($delim_stop)) ? implode(',', $delim_stop) : $delim_stop); ?>" />
                            </div>
                            <p>(or enter bulk list of URLs to automatically import)</p>
                            <hr />
                        </div>
                    </div>
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Transform Filters to Apply
                            </label>
                            <div class="input-group"><?= $check ?></div>
                            <p>Expand list of transform filters by adding to the <i>IMPORT::transforms</i> configuration array</p>
                            <hr />
                            <?php foreach ($transform as $key => $item) :
                                    $callback = $item['callback'] ?? NULL;
                                    echo '<br /><b>' . $key . '</b><br />';
                                    echo (empty($callback)) ? 'ERROR' : $callback->getDescription();
                                  endforeach;
                            ?>
                        </div>
                    </div>
                </div>

                <!-- Input -->
                <div class="row">
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Target URL
                            </label>
                            <div class="input-group">
                                <input class="form-control" name="target_url" id="target_url" size=60 placeholder="http://company.com/page/title" type="text" />
                            </div>
                            <p>Optional destination.  If not set, uses "path" from import URL source as destination.</p>
                            <hr />
                        </div>
                    </div>
                </div>
                <!-- End Input -->

                <!-- Input -->
                <div class="row">
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <input name="choose_import" type="submit" class="btn btn-primary btn-circled" value="Import">
                        </div>
                    </div>
                </div>
                <!-- End Input -->

            </form>
            <!-- End Edit Form -->
           <!-- form message -->
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success contact__msg">
                        <?= $msg ?>
                    </div>
                </div>
            </div>
            <!-- end message -->
        </div>

    </div>
  </div>
