<?php
use SimpleHtml\Transform\Import;
use SimpleHtml\Common\Page\Edit;
use SimpleHtml\Common\Security\Profile;
use SimpleHtml\Common\Generic\Messages;
// upload function
function do_import($url, $transform, $delim_start, $delim_stop, $edit, $message)
{
    $ok   = FALSE;
    $html = Import::import($url, $transform, $delim_start, $delim_stop);
    $key  = $edit->getKeyFromURL($url, HTML_DIR);
    if ($edit->save($key, $html, HTML_DIR, TRUE)) {
        $message->addMessage(Edit::SUCCESS_SAVE);
        $ok = TRUE;
    } else {
        $message->addMessage(Edit::ERROR_SAVE);
    }
    return ($ok) ? $key : FALSE;
}
// process contact post (if any)
// $OBJ == calling instance
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
// check to see if authenticated and feature enabled
$enabled = (isset($config['IMPORT']['enable'])) ? $config['IMPORT']['enable'] : FALSE;
if (!$enabled || Profile::verify($config) === FALSE) {
    Profile::logout();
    $message = Messages::getInstance();
    $message->addMessage('Unable to authenticate');
    header('Location: /');
    exit;
}
// init vars
$total     = 0;
$key       = '';
$edit      = new Edit($config);
$message   = Messages::getInstance();
$transform = $config['IMPORT']['transform'] ?? [];
$trusted   = $config['IMPORT']['trusted_src'] ?? [];
$super_url  = $config['SUPER']['super_url'] ?? Edit::DEFAULT_SUPER;
// check to see if we need to import anything
if (!empty($_POST)) {
    $delim_start = $config['IMPORT']['delim_start'];
    $delim_stop  = $config['IMPORT']['delim_stop'];
    $tmp_trans   = $transform;
    // remove transforms not checked
    $checked = $_POST['transform'] ?? [];
    if (empty($checked) && is_array($checked)) {
        foreach($tmp_trans as $key => $value)
            if (!in_array($key, $checked))
                unset($tmp_trans[$key]);
    }
    // if "import_url" is set, just import from the list
    if (isset($_POST['import_url'])) {
        $url  = strip_tags($_POST['import_url']);
        if (Import::is_trusted($url, $trusted))
            $key = do_import($url, $tmp_trans, $delim_start, $delim_stop, $edit, $message);
        if (!empty($key)) {
            header('Location: ' . $super_url . '/edit?page_key=' . $key);
            exit;
        }
    // otherwise check to see if "import_file" is set
    } elseif (isset($_FILES['import_file'])) {
        $list = Import::get_upload($_FILES['import_file']);
        if (empty($list)) {
            $message->addMessage(Import::ERROR_UPLOAD);
        } else {
            foreach ($list as $url)
                $total += do_import($url, $tmp_trans, $delim_start, $delim_stop, $edit, $message);
        }
    }
}
// build checklist of transforms
$apply = $edit->getListOfPages();
$templ = '<li><input type="checkbox" name="transform[]" value="%s" checked />&nbsp;%s</li>';
$check = '<ul>';
foreach ($transform as $key => $item)
    $check .= sprintf($templ, $key, $item['description']);
$check .= '</ul>' . PHP_EOL;
// get messages
$msg = $message->getMessages() ?? 'Enter a URL to import.  Alternatively you can upload a list of URLs of pages to import.';
?>
  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Import</h1>
          <p class="lead mb-5 text-white-50">Use this page to import pages from another website.
          Enter a URL to import or upload a list of URLs of pages to import.
          Checkmark any transformations you wish to make on imported files.
          To expand the number of transformations you need to add to the <i>IMPORT::transform</i> configuration.</p>
          <?php include ($config['SUPER']['super_menu'] ?? '') ?>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
        <div class="col-lg-6">
            <!-- Edit Form -->
            <form class="choose_form" action="<?= $super_url ?>/import" method="post" enctype="multipart/form-data">

                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Manually One or More URLs to Import
                                <span class="text-danger">*</span>
                            </label>
                            <div class="input-group">
                                <input class="form-control" name="import_url" id="import_url" size=60 placeholder="http://company.com/page/one,http://company.com/page/two,etc" type="text" title="Enter single URL of list of URLs separated by commas"/>
                            </div>
                            <p>(or upload list of URLs to automatically import)</p>
                        </div>
                    </div>
                    <!-- End Input -->
                </div>
                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Upload File with List of URLs to Automatically Import
                                <span class="text-danger">*</span>
                            </label>
                            <div class="input-group"><input type="file" name="import_file" /></div>
                            <p>(or manually enter one or more URLs to import)</p>
                        </div>
                    </div>
                    <!-- End Input -->
                </div>
                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Transforms to Apply
                            </label>
                            <div class="input-group"><?= $check ?></div>
                        </div>
                        <p>Expand list of transforms by adding to the <i>IMPORT::transforms</i> configuration array</p>
                    </div>
                    <!-- End Input -->
                </div>
                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Target URL
                            </label>
                            <div class="input-group">
                                <input class="form-control" name="target_url" id="target_url" size=60 placeholder="http://company.com/page/title" type="text" />
                            </div>
                        </div>
                        <p>Optional destination.  If not set, uses "path" from import URL source as destination.</p>
                    </div>
                    <!-- End Input -->
                </div>
                <div class="row">
                    <!-- Input -->
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <input name="choose_import" type="submit" class="btn btn-primary btn-circled" value="Import">
                        </div>
                    </div>
                    <!-- End Input -->
                </div><!-- row -->

            </form>
            <!-- End Edit Form -->
           <!-- form message -->
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success contact__msg">
                        <?= $msg ?>
                    </div>
                </div>
            </div>
            <!-- end message -->
        </div>

    </div>
  </div>
