<?php
use FileCMS\Transform\Import;
use FileCMS\Common\Page\Edit;
use FileCMS\Common\Security\Profile;
use FileCMS\Common\Generic\Messages;
// process contact post (if any)
// $OBJ == calling instance
if (!empty($OBJ)) {
    $uri    = $OBJ->uri;
    $config = $OBJ->config;
}
// check to see if authenticated and feature enabled
$enabled = (isset($config['TRANSFORM']['enable'])) ? $config['TRANSFORM']['enable'] : FALSE;
if (!$enabled || Profile::verify($config) === FALSE) {
    Profile::logout();
    $message = Messages::getInstance();
    $message->addMessage('Unable to authenticate');
    header('Location: /');
    exit;
}
// init vars
$message   = Messages::getInstance();
$trans_dir = $config['TRANSFORM']['transform_dir'] ?? SRC_DIR . '/Transform';
$trans_field = $config['TRANSFORM']['transform_file_field'] ?? 'transform_file';
// check to see if we need to transform anything
if (!empty($_POST['choose_transform'])) {
}
// build dropdown list of existing pages to transform
$pages = $edit->getListOfPages();
$select = '<select name="page_key" class="form-control" placeholder="Choose" multiple size=12>' . PHP_EOL;
$select .= '<option>' . Edit::CHOOSE_TOP . '</option>' . PHP_EOL;
foreach (array_keys($pages) as $key)
    $select .= '<option>' . $key . '</option>' . PHP_EOL;
$select .= '</select>' . PHP_EOL;
// build list of transforms
$transform_list = '';
if (Transform::load_transforms($transform_dir)) {
    if (!empty(Transform::$container)) {
        foreach (Transform::$container as $class => $obj) {
            $transform_list .= '<h4>' . $class . '</h4>';
            $transform_list .= '<table>';
            $transform_key = md5($class);
            $params = get_object_vars($obj);
            foreach ($params as $key => $value) {
                $sub_key = $transform_key . '_' . $key;
                $transform_list .= '<tr>';
                $transform_list .= '<th>' . $key . '</th>';
                $transform_list .= '<td><input name="' . $sub_key . '" value="' . htmlspecialchars($value) . '"></td>';
                $transform_list .= '</tr>';
            }
            $transform_list .= '</table>';
            $transform_list .= $obj::DESCRIPTION;
        }
    }
}
// get messages
$msg = $message->getMessages() ?? 'Enter a URL to import.  Alternatively you can upload a list of URLs of pages to import.';
if (!empty($bulk))
    foreach ($bulk as $key)
        $msg .= '<br /><a target="_blank" href="/super/edit?page_key=' . $key . '">' . $key . '</a>';
?>
  <!-- Header -->
  <header class="bg-primary py-5 mb-5">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-lg-12">
          <h1 class="display-4 text-white mt-5 mb-2">Transform</h1>
          <p class="lead mb-5 text-white-50">Use this page to filter and transform existing web pages.
          Automatically creates a backup of any page before it is transformed.
          Be sure to preview the page before you save it.
          You are also given the option to restore the page, in which case it restores from the backup file created.
          <?php include ($config['SUPER']['super_menu'] ?? '') ?>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
        <div class="col-lg-12">
            <!-- Edit Form -->
            <form class="choose_form" action="<?= $super_url ?>/transform" method="post" enctype="multipart/form-data">

                <div class="row">
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Choose from Page List (or Enter URL)
                                <span class="text-danger">*</span>
                            </label>
                            <div class="input-group"><?= $select ?></div>
                        </div>
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Upload File with List of Pages to Transform
                                <span class="text-danger">*</span>
                            </label>
                            <div class="input-group"><input type="file" name="<?= $trans_field ?>" /></div>
                            <p>(or manually enter one or more pages to transform)</p>
                            <hr />
                        </div>
                    </div>
                    <div class="col-sm-6 mb-6">
                        <div class="form-group">
                            <label class="h6 small d-block text-uppercase">
                                Transform Filters to Apply
                            </label>
                            <p>Expand list of transform filters by adding to the <i>TRANSFORM::transforms</i> configuration array</p>
                            <hr />
                            <?= $transform_list ?>
                        </div>
                    </div>
                </div>

                <!-- Input -->
                <div class="row">
                    <div class="col-sm-12 mb-12">
                        <div class="form-group">
                            <input name="choose_transform" type="submit" class="btn btn-primary btn-circled" value="Transform">
                        </div>
                    </div>
                </div>
                <!-- End Input -->

            </form>
            <!-- End Edit Form -->
           <!-- form message -->
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success contact__msg">
                        <?= $msg ?>
                    </div>
                </div>
            </div>
            <!-- end message -->
        </div>

    </div>
  </div>
